services:
  proxy-nginx:
    image: ghcr.io/tetrixdev/proxy-nginx:REPLACE_WITH_VERSION
    container_name: proxy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main-network
    restart: always
    logging:
      driver: journald
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  main-network:
    name: main-network
